### ISSUE TITLE
Change resource scope from Cluster to Namespace

### ISSUE THREAD

**Issue by ambientsound** [nais/alerterator#16]
- Change how the resource works
- Find easiest migration path for users (new resource version? pull requests to repos?)
- Make sure resources are migrated

**Comment by Kyrremann** [comment]
# Angrepsplan

Utfordringen er at vi må slette alle alerts og CRD-en til alerts for å kunne bytte fra cluster-scope til namespace-scope.

0. Oppdatere koden til Alerterator til å støtte namespaces
1. Skru av Alerterator
  Dette gjør at endringer i alerts-ressurser ikke blir flyttet over til Alertmanager og Prometheus. Som igjen betyr at vi kan trygt slette alerts-ressurser uten at folk mister alerts fra Alertmanager.
2. Migrere alle alerts.yml i Alerterator-configmap til å ha namespace i navnet
3. Slette alle alerts-ressurser og CRD
4. Deploye ny CRD og Alerterator
5. Migrere/lage PR for alle alerts.yml på github

## Når skal det gjøres?

Vi må bli enige om en dato for å gjøre denne jobben, hvis vi (les: jeg) bidrar med å oppdatere yaml-er, så tenker jeg ikke vi trenger å gi folk så lang frist. Dette vil heller ikke påvirke selve alarmene, men man får så klart ikke lagt til nye alerts, eller fjernet gamle i tidsrommet oppdateringen skjer.

## Hvor lang tid?

Å slette gamle ressurser og legge inn ny CRD er gjort på minutter per cluster. Så estimert til to timer. Kodingen kan gjøres på forhånd, og migrering av gamle alerts kan gjøres etterpå.

**Comment by Kyrremann** [comment]
Da var dette gjort. Meste parten av tiden ble brukt på GCP, da det er treg feedback-loop med github action.
Ellers lærte jeg det er fint å rense ressurser for `resourceVerison` før jeg legger dem ut igjen.

For GCP så savnet jeg også en mulighet til å hindre deploy.
