### ISSUE TITLE
Delete default AlertManager config

### ISSUE THREAD

**Issue by ambientsound** [nais/alerterator#17]
- [x] Migrate AURA/Platform alerts to Alerterator format
- [x] Move route configuration from nais-yaml to Alert resources
- [x] Delete default AlertManager config from nais-yaml

**Comment by Kyrremann** [comment]
* https://github.com/navikt/nais-yaml/blob/master/templates/alertmanager-slack-template.yaml
  * For slack-template, den som bestemmer hvordan slack-meldinger skal se ut
* https://github.com/navikt/nais-yaml/blob/master/templates/alertmanager-template-config.yaml
  * Configen som blir brukt når alerterator oppdaterer configen til alertmanager
