### ISSUE TITLE
Slack konfig for å slå av resolved meldinger

### ISSUE THREAD

**Issue by junnae** [nais/alerterator#31]
Ønsker meg konfig for å kunne slå av "resolved" meldingene i slack, de er ofte bare spam for vår del

**Comment by Kyrremann** [comment]
Ser ut som at vi ikke har lagt til feltet `send_resolved` for Slack. Det kan vi få gjort til uken.
Kan også få lagt til mulighet for eget bilde og ikon.

**Comment by junnae** [comment]
Det er forresten også i grafana mulig å få warningen til å gjenta så og så ofte, frem til den er resolved. Har gjerne brukt det fremfor resolved før. Drømmen hadde jo vært om man evt kunne få resolved meldingen som et reply til den første meldingen

**Comment by junnae** [comment]
Hehe, også vil gjerne kunne få ut verdien av queriet som trigger alarmen

**Comment by Kyrremann** [comment]
> Hehe, også vil gjerne kunne få ut verdien av queriet som trigger alarmen

Lag et nytt issue for det med verdier fra queries.



> Det er forresten også i grafana mulig å få warningen til å gjenta så og så ofte, frem til den er resolved. Har gjerne brukt det fremfor resolved før. Drømmen hadde jo vært om man evt kunne få resolved meldingen som et reply til den første meldingen

Har du sett på disse tre verdiene? https://doc.nais.io/observability/alerts/spec/#specroutegroupwait

Å få resolved som en reply blir vanskelig da vi bruker Slack sitt api for dette. Og de har ikke noe støtte for slik.

**Comment by junnae** [comment]
> > Hehe, også vil gjerne kunne få ut verdien av queriet som trigger alarmen
> 
> Lag et nytt issue for det med verdier fra queries.
> 
> > Det er forresten også i grafana mulig å få warningen til å gjenta så og så ofte, frem til den er resolved. Har gjerne brukt det fremfor resolved før. Drømmen hadde jo vært om man evt kunne få resolved meldingen som et reply til den første meldingen
> 
> Har du sett på disse tre verdiene? https://doc.nais.io/observability/alerts/spec/#specroutegroupwait
> 
> Å få resolved som en reply blir vanskelig da vi bruker Slack sitt api for dette. Og de har ikke noe støtte for slik.

med å grave på internett fant jeg ut at $value gir ut verdien på expressionen! Det kan vi kanskje legge til i doc-en. Men trenger å formatere den litt - får med altfor mange desimaler

**Comment by Kyrremann** [comment]
Bare å komme med PR til dokumentasjonen! 👍
