### ISSUE TITLE
Filtrere alerts på alert-ressursnavn istedetfor teamnavn?

### ISSUE THREAD

**Issue by sisselfladby** [nais/alerterator#7]
Jeg ønsker meg en annen modell på alertene enn å filtrere etter teamnavn.

For større team som jobber på vidt forskjellige applikasjoner hadde det vært fint å kunne ha forskjellige alerts på forskjellige kanaler. I vårt eksempel er vi tre subteam til et stort team, som per nå må dele på èn alert channel. Mange har gjerne ikke noe stort forhold til de andres subteamenes apper, og kanalen vil i større grad oppleves som støy. 

Et annet poeng er at jeg ikke skjønte hva som skjedde da jeg fikk masse ekstravarsler med på kjøpet i den nyopprettede varselkanalen vår etter å ha deployet en alertressurs med et par varsler for èn app. Det opplevdes ikke som forventet oppførsel at jeg da skulle få med alle varslene til hele teamet.

**Comment by jhrv** [comment]
Jeg ser at dette kan gi uventet oppførsel dersom man lager flere `Alert`-ressurser med samme team, og prøver å angi ulike Slack-kanaler på disse. Vi burde kunne ordne en rutingmekanisme som tar høyde for dette 👍

**Comment by Kyrremann** [comment]
Da skal dette være løst: https://github.com/nais/alerterator/commit/19b0dfe8f72f219ea661b0d56dc98d662b943b28

For at endringen skal ta effekt for deg @sisselfladby, så må du kjøre `kubectl apply -f alert.yaml` på nytt. Da vil alertsene dine bli oppdatert.
